---
title: Lema de Yoneda
---


#+begin_theorem
*Lema de Yoneda*
Sea $G : {\cal C} \longrightarrow \mathtt{Set}$ un funtor covariante. Fijado $A \in \mathrm{obj}({\cal C})$, tenemos una
biyección entre las transformaciones naturales del funtor $\mathrm{Hom}(A,-)$ a
$G$ y los elementos del conjunto $G(A)$:

\[
y : \mathrm{Nat}(\mathrm{Hom}_{\cal C}(A,-),G) \longrightarrow G(A)
\]

Que viene dada por $y(\tau) = \tau_A(1_A)$, la imagen de la identidad por la
transformación natural.
#+end_theorem

#+begin_proof
*Demostración.*
Dado cualquier $p$ crearemos la única transformación natural que cumple
$\eta_A(1_A) = p$. Por definición de transformación natural, sabemos que debe
cumplir el siguiente diagrama conmutativo:

\[\require{AMScd}\begin{CD}
\mathrm{Hom}(A,A)     @>{f \circ \_}>>  \mathrm{Hom}(A,B)\\
@VV{\eta_{A}}V        @VV{\eta_B}V\\
GA     @>{Gf}>>  GB
\end{CD}\]

Lo que deja determinado a cualquier $\eta_B(f)$, y por tanto a toda la función:

\[\eta_B(f) = \eta_B(f\circ id) = Gf(\eta_A(id_A)) = Gf(p) \]

Nos falta comprobar que la función así construida es de hecho una 
transformación natural. Es decir, que cumple el siguiente diagrama
conmutativo:

\[\require{AMScd}\begin{CD}
\mathrm{Hom}(A,B)     @>{g \circ \_}>>  \mathrm{Hom}(A,C)\\
@VV{\eta_B}V        @VV{\eta_C}V\\
GB     @>{Gg}>>  GC
\end{CD}\]


Y de hecho, dado cualquier elemento $f \in \mathrm{Hom}(A,B)$ tenemos:

\[Gg\circ \eta(f) = Gg \circ Gf(p) = G(g\circ f)(p) = \eta(g\circ f)\]
#+end_proof

** Lema de Yoneda (caso contravariante)
Si aplicamos Yoneda sobre $\mathcal{C}^{op}$, dado $G : {\cal C} \longrightarrow \mathtt{Set}$ *contravariante*
y fijado $A \in obj({\cal C})$; existe una biyección entre las transformaciones naturales
del funtor $Hom(-,A)$ a $G$ y los elementos del conjunto $G(A)$:

\[
y : \mathrm{Nat}(\mathrm{Hom}_{\cal C}(-,A),G) \longrightarrow G(A)
\]

Que viene de nuevo dada por $y(\tau) = \tau_A(1_A)$.

** Referencias y enlaces

 [1] J. Rotman, An Introduction to Homological Algebra.

 [2] Bartosz Milewski's Programming Cafe.
     [[https://bartoszmilewski.com/2015/09/01/the-yoneda-lemma/][The Yoneda Lemma]]

 [3] The Catsters.
     [[https://www.youtube.com/watch?v=TLMxHB19khE][Representables and Yoneda 3]]
